### ISSUE TITLE
Issues with using skgarden's RandomForestQuantileRegressor

### ISSUE THREAD

**Issue by tanvirachy** [scikit-garden/scikit-garden#109]
Hi when I try using skgarden's RandomForestQuantileRegressor, I get the following error:
File "C:\Users\.......\anaconda3\lib\site-packages\skgarden\quantile\ensemble.py", line 461, in __init__
    super(RandomForestQuantileRegressor, self).__init__(

TypeError: __init__() missing 1 required positional argument: 'estimator'

Also when I try running the boston example from 
https://scikit-garden.github.io/examples/QuantileRegressionForests/#quantile-regression-forests

I get this error:

 File "C:\Users\.....\anaconda3\lib\site-packages\sklearn\model_selection\_split.py", line 451, in __init__
    super().__init__(n_splits=n_splits, shuffle=shuffle, random_state=random_state)

  File "C:\Users\.......\anaconda3\lib\site-packages\sklearn\model_selection\_split.py", line 308, in __init__
    raise ValueError(

ValueError: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.

The boston example code is as follows:
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from skgarden import RandomForestQuantileRegressor

X, y = data,target
kf = KFold(n_splits=5, random_state=0)
rfqr = RandomForestQuantileRegressor(
    random_state=0, min_samples_split=10, n_estimators=1000)

**Comment by Hee-beep** [comment]
Well...I got in trouble using the same function, skgarden's RandomForestQuantileRegressor.

I guess I have problems when loading skgarden:
from skgarden import RandomForestQuantileRegressor

Here is my error:
Traceback (most recent call last):
  File "D:/Program Files (x86)/../QRRF.py", line 4, in <module>
    from skgarden import RandomForestQuantileRegressor
  File "D:\anaconda3\envs\Wuhan\lib\site-packages\skgarden\__init__.py", line 3, in <module>
    from .mondrian import MondrianForestClassifier
  File "D:\anaconda3\envs\Wuhan\lib\site-packages\skgarden\mondrian\__init__.py", line 1, in <module>
    from .ensemble import MondrianForestClassifier
  File "D:\anaconda3\envs\Wuhan\lib\site-packages\skgarden\mondrian\ensemble\__init__.py", line 1, in <module>
    from .forest import MondrianForestClassifier
  File "D:\anaconda3\envs\Wuhan\lib\site-packages\skgarden\mondrian\ensemble\forest.py", line 9, in <module>
    from ..tree import MondrianTreeClassifier
  File "D:\anaconda3\envs\Wuhan\lib\site-packages\skgarden\mondrian\tree\__init__.py", line 6, in <module>
    from .tree import MondrianTreeRegressor
  File "D:\anaconda3\envs\Wuhan\lib\site-packages\skgarden\mondrian\tree\tree.py", line 31, in <module>
    from sklearn.externals import six
ImportError: cannot import name 'six'

I didn't figure out why it would trace back to sklearn. to load RandomForestQuantileRegressor, which was put in skgarden.

**Comment by jasperroebroek** [comment]
Unfortunately this packages has not been maintained for years and is not up to date with the latest versions of scikit-learn. I have attempted to make an updated version of the package: `sklearn-quantile`.

**Comment by reidjohnson** [comment]
For an actively maintained quantile regression forest implementation specifically, I'll also pitch [quantile-forest](https://github.com/zillow/quantile-forest).
