### ISSUE TITLE
build_ext fails with Python >= 3.0

### ISSUE THREAD

**Issue by ecederstrand** [scikit-garden/scikit-garden#111]
Getting this stack trace when I try to run `setup.py build_ext` on the master branch:

```bash
$ python3 setup.py build_ext bdist_wheel
[...]
Error compiling Cython file:
------------------------------------------------------------
...

# See _utils.pyx for details.

import numpy as np
cimport numpy as np
from _tree cimport Node
^
------------------------------------------------------------

skgarden/mondrian/tree/_utils.pxd:13:0: '_tree.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...

# See _utils.pyx for details.

import numpy as np
cimport numpy as np
from _tree cimport Node
^
------------------------------------------------------------

skgarden/mondrian/tree/_utils.pxd:13:0: '_tree/Node.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
    (DTYPE_t*)
    (SIZE_t*)
    (unsigned char*)
    (DOUBLE_t*)
    (DOUBLE_t**)
    (Node*)
     ^
------------------------------------------------------------

skgarden/mondrian/tree/_utils.pxd:40:5: 'Node' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    (SIZE_t*)
    (unsigned char*)
    (DOUBLE_t*)
    (DOUBLE_t**)
    (Node*)
    (Node**)
     ^
------------------------------------------------------------

skgarden/mondrian/tree/_utils.pxd:41:5: 'Node' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    (SIZE_t*)
    (unsigned char*)
    (DOUBLE_t*)
    (DOUBLE_t**)
    (Node*)
    (Node**)
    ^
------------------------------------------------------------

skgarden/mondrian/tree/_utils.pxd:41:4: Type specified multiple times

Error compiling Cython file:
------------------------------------------------------------
...
        self.sum_total = NULL
        self.sum_left = NULL
        self.sum_right = NULL
        self.n_classes = NULL

        safe_realloc(&self.n_classes, n_outputs)
                    ^
------------------------------------------------------------

skgarden/mondrian/tree/_criterion.pyx:563:20: ambiguous overloaded method

Error compiling Cython file:
------------------------------------------------------------
...
        self.sum_total = NULL
        self.sum_left = NULL
        self.sum_right = NULL
        self.n_classes = NULL

        safe_realloc(&self.n_classes, n_outputs)
        ^
------------------------------------------------------------

skgarden/mondrian/tree/_criterion.pyx:563:8: Invalid use of fused types, type cannot be specialized
Traceback (most recent call last):
  File "/tmp/tmp.0I0j9ybVxa/scikit-garden/setup.py", line 51, in <module>
    setup(name=DISTNAME,
  File "lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "lib/python3.9/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/tmp/tmp.0I0j9ybVxa/scikit-garden/setup.py", line 46, in finalize_options
    self.distribution.ext_modules[:] = cythonize(self.distribution.ext_modules, force=self.force)
  File "/tmp/tmp.0I0j9ybVxa/scikit-garden/.eggs/Cython-3.0.0-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/tmp/tmp.0I0j9ybVxa/scikit-garden/.eggs/Cython-3.0.0-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: skgarden/mondrian/tree/_criterion.pyx
```

**Comment by christianthilker** [comment]
I get the same error when I try to install scikit-garden from pip.

**Comment by ecederstrand** [comment]
Fixed in https://github.com/scikit-garden/scikit-garden/pull/112

**Comment by ecederstrand** [comment]
No longer using this package. Closing.
