### ISSUE TITLE
Installation issues using latest

### ISSUE THREAD

**Issue by Martin-Molinero** [scikit-garden/scikit-garden#117]
```
# pip install git+https://github.com/scikit-garden/scikit-garden.git
Collecting git+https://github.com/scikit-garden/scikit-garden.git
  Cloning https://github.com/scikit-garden/scikit-garden.git to /tmp/pip-req-build-jih70vbm
  Running command git clone --filter=blob:none --quiet https://github.com/scikit-garden/scikit-garden.git /tmp/pip-req-build-jih70vbm
  Resolved https://github.com/scikit-garden/scikit-garden.git to commit fbd9a5b5f0c0ebddd44516f28ac14c538354e549
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [246 lines of output]
      /opt/miniconda3/lib/python3.11/site-packages/setuptools/dist.py:450: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      /opt/miniconda3/lib/python3.11/site-packages/setuptools/dist.py:450: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'license-file' will not be supported in future
              versions. Please use the underscore name 'license_file' instead.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      /opt/miniconda3/lib/python3.11/site-packages/setuptools/__init__.py:88: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      /opt/miniconda3/lib/python3.11/site-packages/setuptools/dist.py:450: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      /opt/miniconda3/lib/python3.11/site-packages/setuptools/dist.py:450: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'license-file' will not be supported in future
              versions. Please use the underscore name 'license_file' instead.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      running egg_info
      creating /tmp/pip-pip-egg-info-aka1bj6x/scikit_garden.egg-info
      writing /tmp/pip-pip-egg-info-aka1bj6x/scikit_garden.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-aka1bj6x/scikit_garden.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-aka1bj6x/scikit_garden.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-aka1bj6x/scikit_garden.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-aka1bj6x/scikit_garden.egg-info/SOURCES.txt'
      /opt/miniconda3/lib/python3.11/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-req-build-jih70vbm/skgarden/mondrian/tree/_criterion.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      warning: skgarden/mondrian/tree/_criterion.pxd:58:45: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pxd:59:40: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pxd:60:48: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pxd:61:57: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pyx:56:45: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pyx:85:40: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pyx:93:48: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pyx:100:57: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pyx:284:45: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pyx:326:40: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pyx:337:48: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pyx:348:57: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pyx:600:76: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pyx:669:40: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pyx:696:48: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_criterion.pyx:723:57: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_utils.pxd:44:75: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: skgarden/mondrian/tree/_utils.pxd:86:61: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

      # See _utils.pyx for details.

      import numpy as np
      cimport numpy as np
      from _tree cimport Node
      ^
      ------------------------------------------------------------

      skgarden/mondrian/tree/_utils.pxd:13:0: '_tree.pxd' not found

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

      # See _utils.pyx for details.

      import numpy as np
      cimport numpy as np
      from _tree cimport Node
      ^
      ------------------------------------------------------------

      skgarden/mondrian/tree/_utils.pxd:13:0: '_tree/Node.pxd' not found

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          (DTYPE_t*)
          (SIZE_t*)
          (unsigned char*)
          (DOUBLE_t*)
          (DOUBLE_t**)
          (Node*)
           ^
      ------------------------------------------------------------

      skgarden/mondrian/tree/_utils.pxd:40:5: 'Node' is not a type identifier

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          (SIZE_t*)
          (unsigned char*)
          (DOUBLE_t*)
          (DOUBLE_t**)
          (Node*)
          (Node**)
           ^
      ------------------------------------------------------------

      skgarden/mondrian/tree/_utils.pxd:41:5: 'Node' is not a type identifier

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          (SIZE_t*)
          (unsigned char*)
          (DOUBLE_t*)
          (DOUBLE_t**)
          (Node*)
          (Node**)
          ^
      ------------------------------------------------------------

      skgarden/mondrian/tree/_utils.pxd:41:4: Type specified multiple times

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self.sum_total = NULL
              self.sum_left = NULL
              self.sum_right = NULL
              self.n_classes = NULL

              safe_realloc(&self.n_classes, n_outputs)
                          ^
      ------------------------------------------------------------

      skgarden/mondrian/tree/_criterion.pyx:563:20: ambiguous overloaded method

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self.sum_total = NULL
              self.sum_left = NULL
              self.sum_right = NULL
              self.n_classes = NULL

              safe_realloc(&self.n_classes, n_outputs)
              ^
      ------------------------------------------------------------

      skgarden/mondrian/tree/_criterion.pyx:563:8: Invalid use of fused types, type cannot be specialized
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-jih70vbm/setup.py", line 51, in <module>
          setup(name=DISTNAME,
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/__init__.py", line 111, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
          self.run_command(cmd)
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/dist.py", line 948, in run_command
          super().run_command(command)
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 311, in run
          self.find_sources()
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 319, in find_sources
          mm.run()
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 540, in run
          self.add_defaults()
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/command/sdist.py", line 105, in add_defaults
          super().add_defaults()
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 334, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 303, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/tmp/pip-req-build-jih70vbm/setup.py", line 46, in finalize_options
          self.distribution.ext_modules[:] = cythonize(self.distribution.ext_modules, force=self.force)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/opt/miniconda3/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: skgarden/mondrian/tree/_criterion.pyx
      Compiling skgarden/mondrian/tree/_tree.pyx because it changed.
      Compiling skgarden/mondrian/tree/_splitter.pyx because it changed.
      Compiling skgarden/mondrian/tree/_criterion.pyx because it changed.
      Compiling skgarden/mondrian/tree/_utils.pyx because it changed.
      [1/4] Cythonizing skgarden/mondrian/tree/_criterion.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

- OS: linux 64
- Python 3.11.11
- cython 3.0.9
- setuptools 73.0.1
- scipy 1.11.4
- numpy 1.26.4

**Comment by kbwaj** [comment]
Received the same error and tried multiple older versions of python and dependencies but still not working. Is there a list of dependencies and versions anywhere?

**Comment by SimonEnsemble** [comment]
got it to install Python 3.12.0 via:
```bash
uv venv --python 3.12 mondrian
source mondrian/bin/activate
```

clone the repo. `cd` into it.
```bash
git fetch origin pull/116/head:pr-116 # a pending pull request
git checkout pr-116
uv pip install -e .
```
