### ISSUE TITLE
Build failure when installing as dependency

### ISSUE THREAD

**Issue by betatim** [scikit-garden/scikit-garden#20]
Below an extremely long log output of a failure when trying to install `scikit-optimize` from master without first installing scikit-garden or cython in a fresh python3.6 conda environment. Not sure I really understand why it fails, or what went wrong.

```
$ pip install https://github.com/scikit-optimize/scikit-optimize/archive/master.zip
Collecting https://github.com/scikit-optimize/scikit-optimize/archive/master.zip
  Downloading https://github.com/scikit-optimize/scikit-optimize/archive/master.zip (1.4MB)
    100% |████████████████████████████████| 1.4MB 790kB/s 
Requirement already satisfied: numpy in ./anaconda/envs/robot-phys/lib/python3.6/site-packages (from scikit-optimize==0.3)
Requirement already satisfied: scipy in ./anaconda/envs/robot-phys/lib/python3.6/site-packages (from scikit-optimize==0.3)
Requirement already satisfied: scikit-learn>=0.18 in ./anaconda/envs/robot-phys/lib/python3.6/site-packages (from scikit-optimize==0.3)
Collecting scikit-garden (from scikit-optimize==0.3)
  Using cached scikit-garden-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Unable to find pgen, not compiling formal grammar.
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    /tmp/easy_install-vnba_vee/Cython-0.25.2/Cython/Compiler/FlowControl.c: In function ‘__Pyx_PyInt_LshiftObjC’:
    /tmp/easy_install-vnba_vee/Cython-0.25.2/Cython/Compiler/FlowControl.c:39765:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                     if (unlikely(!(b < sizeof(long)*8 && a == x >> b)) && a) {
                                      ^
    /tmp/easy_install-vnba_vee/Cython-0.25.2/Cython/Compiler/FlowControl.c:608:43: note: in definition of macro ‘unlikely’
       #define unlikely(x) __builtin_expect(!!(x), 0)
                                               ^
    
    Installed /tmp/pip-build-kugr7f0w/scikit-garden/.eggs/Cython-0.25.2-py3.6-linux-x86_64.egg
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    import numpy as np
    cimport numpy as np
    np.import_array()
    
    from ._utils cimport log
    ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:29:0: 'skgarden/mondrian/tree/_utils.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    import numpy as np
    cimport numpy as np
    np.import_array()
    
    from ._utils cimport log
    ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:29:0: 'skgarden/mondrian/tree/_utils/log.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import numpy as np
    cimport numpy as np
    np.import_array()
    
    from ._utils cimport log
    from ._utils cimport safe_realloc
    ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:30:0: 'skgarden/mondrian/tree/_utils/safe_realloc.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cimport numpy as np
    np.import_array()
    
    from ._utils cimport log
    from ._utils cimport safe_realloc
    from ._utils cimport sizet_ptr_to_ndarray
    ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:31:0: 'skgarden/mondrian/tree/_utils/sizet_ptr_to_ndarray.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            return {}
    
        def __setstate__(self, d):
            pass
    
        cdef int init(self, DOUBLE_t* y, SIZE_t y_stride, DOUBLE_t* sample_weight,
                           ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:54:24: 'DOUBLE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            return {}
    
        def __setstate__(self, d):
            pass
    
        cdef int init(self, DOUBLE_t* y, SIZE_t y_stride, DOUBLE_t* sample_weight,
                                        ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:54:37: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            return {}
    
        def __setstate__(self, d):
            pass
    
        cdef int init(self, DOUBLE_t* y, SIZE_t y_stride, DOUBLE_t* sample_weight,
                                                         ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:54:54: 'DOUBLE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        def __setstate__(self, d):
            pass
    
        cdef int init(self, DOUBLE_t* y, SIZE_t y_stride, DOUBLE_t* sample_weight,
                      double weighted_n_samples, SIZE_t* samples, SIZE_t start,
                                                ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:55:45: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        def __setstate__(self, d):
            pass
    
        cdef int init(self, DOUBLE_t* y, SIZE_t y_stride, DOUBLE_t* sample_weight,
                      double weighted_n_samples, SIZE_t* samples, SIZE_t start,
                                                                 ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:55:62: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def __setstate__(self, d):
            pass
    
        cdef int init(self, DOUBLE_t* y, SIZE_t y_stride, DOUBLE_t* sample_weight,
                      double weighted_n_samples, SIZE_t* samples, SIZE_t start,
                      SIZE_t end) nogil except -1:
                     ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:56:18: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
            This method must be implemented by the subclass.
            """
            pass
    
        cdef int update(self, SIZE_t new_pos) nogil except -1:
                             ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:100:26: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                = (\sum_i^n y_i ** 2) - n_samples * y_bar ** 2
        """
    
        cdef double sq_sum_total
    
        def __cinit__(self, SIZE_t n_outputs, SIZE_t n_samples):
                           ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:226:24: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                = (\sum_i^n y_i ** 2) - n_samples * y_bar ** 2
        """
    
        cdef double sq_sum_total
    
        def __cinit__(self, SIZE_t n_outputs, SIZE_t n_samples):
                                             ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:226:42: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                raise MemoryError()
    
        def __reduce__(self):
            return (type(self), (self.n_outputs, self.n_samples), self.__getstate__())
    
        cdef int init(self, DOUBLE_t* y, SIZE_t y_stride, DOUBLE_t* sample_weight,
                           ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:276:24: 'DOUBLE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                raise MemoryError()
    
        def __reduce__(self):
            return (type(self), (self.n_outputs, self.n_samples), self.__getstate__())
    
        cdef int init(self, DOUBLE_t* y, SIZE_t y_stride, DOUBLE_t* sample_weight,
                                        ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:276:37: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                raise MemoryError()
    
        def __reduce__(self):
            return (type(self), (self.n_outputs, self.n_samples), self.__getstate__())
    
        cdef int init(self, DOUBLE_t* y, SIZE_t y_stride, DOUBLE_t* sample_weight,
                                                         ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:276:54: 'DOUBLE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        def __reduce__(self):
            return (type(self), (self.n_outputs, self.n_samples), self.__getstate__())
    
        cdef int init(self, DOUBLE_t* y, SIZE_t y_stride, DOUBLE_t* sample_weight,
                      double weighted_n_samples, SIZE_t* samples, SIZE_t start,
                                                ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:277:45: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        def __reduce__(self):
            return (type(self), (self.n_outputs, self.n_samples), self.__getstate__())
    
        cdef int init(self, DOUBLE_t* y, SIZE_t y_stride, DOUBLE_t* sample_weight,
                      double weighted_n_samples, SIZE_t* samples, SIZE_t start,
                                                                 ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:277:62: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def __reduce__(self):
            return (type(self), (self.n_outputs, self.n_samples), self.__getstate__())
    
        cdef int init(self, DOUBLE_t* y, SIZE_t y_stride, DOUBLE_t* sample_weight,
                      double weighted_n_samples, SIZE_t* samples, SIZE_t start,
                      SIZE_t end) nogil except -1:
                     ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:278:18: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            self.weighted_n_right = 0.0
            self.weighted_n_left = self.weighted_n_node_samples
            self.pos = self.end
            return 0
    
        cdef int update(self, SIZE_t new_pos) nogil except -1:
                             ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:342:26: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    
    cdef class ClassificationCriterion(Criterion):
        """Abstract criterion for classification."""
    
        cdef SIZE_t* n_classes
            ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:517:9: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    cdef class ClassificationCriterion(Criterion):
        """Abstract criterion for classification."""
    
        cdef SIZE_t* n_classes
        cdef SIZE_t sum_stride
            ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:518:9: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """Abstract criterion for classification."""
    
        cdef SIZE_t* n_classes
        cdef SIZE_t sum_stride
    
        def __cinit__(self, SIZE_t n_outputs,
                           ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:520:24: 'SIZE_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cdef SIZE_t* n_classes
        cdef SIZE_t sum_stride
    
        def __cinit__(self, SIZE_t n_outputs,
                      np.ndarray[SIZE_t, ndim=1] n_classes):
                                      ^
    ------------------------------------------------------------
    
    skgarden/mondrian/tree/_criterion.pyx:521:35: Invalid type.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kugr7f0w/scikit-garden/setup.py", line 61, in <module>
        setup_requires=["cython"])
      File "/home/thead/anaconda/envs/robot-phys/lib/python3.6/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-build-kugr7f0w/scikit-garden/setup.py", line 25, in configuration
        config.add_subpackage('skgarden')
      File "/home/thead/anaconda/envs/robot-phys/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "/home/thead/anaconda/envs/robot-phys/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "/home/thead/anaconda/envs/robot-phys/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skgarden/setup.py", line 9, in configuration
        config.add_subpackage("mondrian")
      File "/home/thead/anaconda/envs/robot-phys/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "/home/thead/anaconda/envs/robot-phys/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "/home/thead/anaconda/envs/robot-phys/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skgarden/mondrian/setup.py", line 25, in configuration
        config.ext_modules = cythonize(config.ext_modules)
      File "/tmp/pip-build-kugr7f0w/scikit-garden/.eggs/Cython-0.25.2-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 934, in cythonize
        cythonize_one(*args)
      File "/tmp/pip-build-kugr7f0w/scikit-garden/.eggs/Cython-0.25.2-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1056, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: skgarden/mondrian/tree/_criterion.pyx
    Appending skgarden.mondrian.tree configuration to skgarden.mondrian
    Ignoring attempt to set 'name' (from 'skgarden.mondrian' to 'skgarden.mondrian.tree')
    Appending skgarden.mondrian.ensemble configuration to skgarden.mondrian
    Ignoring attempt to set 'name' (from 'skgarden.mondrian' to 'skgarden.mondrian.ensemble')
    skgarden/mondrian/tree/_tree.pyx: cannot find cimported module '._utils'
    skgarden/mondrian/tree/_splitter.pyx: cannot find cimported module '._utils'
    skgarden/mondrian/tree/_splitter.pyx: cannot find cimported module '._criterion'
    skgarden/mondrian/tree/_criterion.pyx: cannot find cimported module '._utils'
    Compiling skgarden/mondrian/tree/_tree.pyx because it depends on /tmp/pip-build-kugr7f0w/scikit-garden/.eggs/Cython-0.25.2-py3.6-linux-x86_64.egg/Cython/Includes/cpython/method.pxd.
    Compiling skgarden/mondrian/tree/_splitter.pyx because it depends on /tmp/pip-build-kugr7f0w/scikit-garden/.eggs/Cython-0.25.2-py3.6-linux-x86_64.egg/Cython/Includes/cpython/buffer.pxd.
    Compiling skgarden/mondrian/tree/_criterion.pyx because it depends on /tmp/pip-build-kugr7f0w/scikit-garden/.eggs/Cython-0.25.2-py3.6-linux-x86_64.egg/Cython/Includes/cpython/buffer.pxd.
    Compiling skgarden/mondrian/tree/_utils.pyx because it depends on /tmp/pip-build-kugr7f0w/scikit-garden/.eggs/Cython-0.25.2-py3.6-linux-x86_64.egg/Cython/Includes/cpython/buffer.pxd.
    [1/4] Cythonizing skgarden/mondrian/tree/_criterion.pyx
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kugr7f0w/scikit-garden/
```

**Comment by MechCoder** [comment]
:/ I don't have a laptop with ubnutu right now, but does just `pip install scikit-garden` work?

**Comment by betatim** [comment]
I think so. Will give it a try because this afternoon I jsut explicitly installed cython and then reran the above command and it worked. Was pretty surprised that worked, but :man_shrugging: what do you know.

**Comment by iaroslav-ai** [comment]
Can confirm this issue can be reproduced on my Ubuntu 16.04 machine (output very similar to that of @betatim). @betatim, how exactly did you install cython? I tried installing using `pip3 install cython`, but then I still get the error. Did you install anything else by any chance?

**Comment by MechCoder** [comment]
I pushed another release just now that does not ignore the template `.pxd` files in MANIFEST.in. I no longer reproduce the problem.

Can you please verify?

**Comment by MechCoder** [comment]
Both `pip install scikit-garden` and `pip install https://github.com/scikit-optimize/scikit-optimize/archive/master.zip` work

**Comment by iaroslav-ai** [comment]
Awesome, it does work now! :D

**Comment by MechCoder** [comment]
Great, not sure whether to be happy that no-one tried it out or whether to be sad that no-one tried it out.

**Comment by glouppe** [comment]
Thanks for the fix! That was probably my fault all along :x

**Comment by MechCoder** [comment]
I'd be happy to share the blame but it was my mistake to not check the pacakged dist before pushing, I don't know how it worked before though :|

**Comment by betatim** [comment]
@iaroslav-ai I think I did `conda install cython`, pretty sure I didn't install anything else.

Thanks for the fix!
