### ISSUE TITLE
numpy required to run setup.py

### ISSUE THREAD

**Issue by betatim** [scikit-garden/scikit-garden#23]
setup.py imports `numpy` which means that you need to run two commands to get things installed:
```
pip install numpy
pip install scikit-optimize
```
if I just run the latter then it installs numpy during the install procedure but that isn't yet available when scikit-garden's `setup.py` is executed:
```
$ pip install https://github.com/scikit-optimize/scikit-optimize/archive/master.zip
Collecting https://github.com/scikit-optimize/scikit-optimize/archive/master.zip
  Downloading https://github.com/scikit-optimize/scikit-optimize/archive/master.zip
     / 1.4MB 15.1MB/s
Collecting numpy (from scikit-optimize==0.3)
  Downloading numpy-1.13.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.5MB)
    100% |████████████████████████████████| 4.5MB 143kB/s 
Collecting scipy (from scikit-optimize==0.3)
  Downloading scipy-0.19.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (16.2MB)
    100% |████████████████████████████████| 16.2MB 41kB/s 
Collecting scikit-learn>=0.18 (from scikit-optimize==0.3)
  Downloading scikit_learn-0.18.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (7.2MB)
    100% |████████████████████████████████| 7.2MB 90kB/s 
Collecting scikit-garden (from scikit-optimize==0.3)
  Using cached scikit-garden-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bh/pvgck_ms7g95dxp3zj_6x_qw0000gn/T/pip-build-bkdlbfp5/scikit-garden/setup.py", line 6, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
```

**Comment by betatim** [comment]
I'd submit a PR but I don't understand why `numpy` is imported in the first place in `setup.py` :-/

**Comment by MechCoder** [comment]
If I replace `from numpy.distutils.core import setup` with `from setuptools import setup`, `setup.py` fails with this error. 

```
setup() arguments must *always* be /-separated paths relative to the
setup.py directory, *never* absolute paths.
```

I'm in no mood currently for build script hacking, so feel free to be my guest :D :D

**Comment by betatim** [comment]
Do you know why there are so many `setup.py` files also in the subdirectories?

**Comment by betatim** [comment]
Seems like there is no way around having to import `numpy` in `setup.py` as it is needed to retrieve the path to the header.

**Comment by betatim** [comment]
[This SO article](https://stackoverflow.com/questions/2379898/make-distutils-look-for-numpy-header-files-in-the-correct-place/42163080#42163080) suggests there is a way to do this without having to install `numpy` by hand beforehand.

via @pelson 👋

**Comment by DandyDev** [comment]
Importing one of the dependencies inside `setup.py` is an exceptionally bad idea. What _might_ work is including numpy in the `setup_required` argument.

**Comment by betatim** [comment]
Do you want to take a stab at implementing the solution mentioned in the SO article linked in the previous comment?

**Comment by SmokinCaterpillar** [comment]
Hey, have the same issue in a build pipeline on gitlab ci, I use scikit garden inside a docker container as numpy is requirement in setup.py. Anyone working on a fix right now?

**Comment by ecederstrand** [comment]
I'm also hitting this. I think #77 fixes the issue cleanly by adding to `setup_requires` and creating a custom `build_ext` step.

I don't know why the tests were failing in that PR, but I can't see how the failures are related directly to the PR. Can someone trigger a new build in Travis?

**Comment by Servot** [comment]
Has there been any progress on this issue or does someone know a work-around? I'm running into this issue because I'm trying to build an Azure Function where the environment is build using a requirement.txt

**Comment by mzjp2** [comment]
Has there been any progress on this?
