### ISSUE TITLE
ValueError: bad input shape

### ISSUE THREAD

**Issue by YanyanNIE** [scikit-garden/scikit-garden#62]
I am using **`RandomForestQuantileRegressor.fit(X, y)`**

And there is a part of [doc](https://scikit-garden.github.io/api/#skgardenquantile_1):
> Parameters
>
> X (array-like or sparse matrix, shape = [n_samples, n_features])
>
> The training input samples. Internally, it will be converted to dtype=np.float32 and if a sparse matrix is provided to a sparse csc_matrix.
>
> y (array-like, shape = [n_samples] or [n_samples, n_outputs])

In my codes, y with the shape [n_samples, n_outputs],
```
type of X <class 'pandas.core.frame.DataFrame'> dim of X (83, 12)
type of y <class 'pandas.core.frame.DataFrame'> dim of y (83, 5)
```

But there is the ValueError:
```
File "random_forest_quantiles.py", line 217, in fit_and_forecast_RF
    regr.fit(X, y)
  File "/var/task/skgarden/quantile/ensemble.py", line 81, in fit
    X, y, accept_sparse="csc", dtype=np.float32, multi_output=False)
  File "/var/task/sklearn/utils/validation.py", line 578, in check_X_y
    y = column_or_1d(y, warn=True)
  File "/var/task/sklearn/utils/validation.py", line 614, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape (83, 5)
```
After we change the code in `skgarden/quantile/ensemble.py` to : 
```
X, y = check_X_y(
            X, y, accept_sparse="csc", dtype=np.float32, multi_output=True)
```
then the error doesn't exist. So i think there is a bug in the source code?

And could you fix the bug? Thanks!

**Comment by lxw0109** [comment]
I got the same error.  
I tried `svm.SVC`, `naive_bayes.GaussianNB`, `linear_model.LogisticRegression`, all of these 3 models raised the same error as follows(complaining the shape of `y`).

> ValueError: bad input shape (32, 5)

However `neighbors.KNeighborsClassifier`, `tree.DecisionTreeClassifier`, `neural_network.MLPClassifier` does NOT raise the error.  

Anybody help? Thank you~

**Comment by vision72** [comment]
Hello Everyone, the problem you all going through is very simple,
First, you can change the data you are using,
(else..)Secondly, you see "bad shape (83, 5)", means that the samples are not matching and they must match in number..
You can try to alter the sizes or use various tricks with the Data.
Hope this Helps-

**Comment by fadeawaygod** [comment]
Maybe you can try LabelEncoder but OntHotEncoder on the Y.

**Comment by RexKing6** [comment]
I got the same error. I clearly know that we should use LabelEncoder to make sure that label is (n,). However, if I want to regression to get more that one outputs, I have no idea.

**Comment by ravindragantasala** [comment]
Check up how the way you splitted your data...

**Comment by ArijitN5** [comment]
ValueError                                Traceback (most recent call last)
<ipython-input-67-8a1929bc1565> in <module>
     18 
     19 #model for testing data
---> 20 ey_prdt=eclf.predict(x_test)
     21 
     22 precision, recall, fscore, support = score(ey_prdt, y_prdt)

~/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/voting_classifier.py in predict(self, X)
    238                 axis=1, arr=predictions)
    239 
--> 240         maj = self.le_.inverse_transform(maj)
    241 
    242         return maj

~/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py in inverse_transform(self, y)
    271         """
    272         check_is_fitted(self, 'classes_')
--> 273         y = column_or_1d(y, warn=True)
    274         # inverse transform of empty array is empty array
    275         if _num_samples(y) == 0:

~/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py in column_or_1d(y, warn)
    795         return np.ravel(y)
    796 
--> 797     raise ValueError("bad input shape {0}".format(shape))
    798 
    799 

ValueError: bad input shape (1, 6)

**Comment by buildhigh20** [comment]
> Maybe you can try LabelEncoder instead of OntHotEncoder on the Y. It results the shape of y (83, 1) instead of (83, 5).

Where I will change this part.?

**Comment by nimafo** [comment]
Hi, did you solve this issue?
